version: '3.3'

services:
  test_client:
    build: 
      context: ./
      dockerfile: DockerfileTest

    networks:
      - rabbitmq
    depends_on:
      - rabbitmq
    stop_signal: SIGINT
    volumes:
      - ./coverage:/usr/src/app/coverage
  rabbitmq:
    image: rabbitmq:3.9
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
    networks:
      - rabbitmq
    stop_signal: SIGINT

networks:
  rabbitmq:
    name: rabbitmq
