version: '3.3'

services:
  test_server:
    build: 
      context: ./
      dockerfile: DockerfileTest

    networks:
      - rabbitmq
    depends_on:
      - rabbitmq_1
  rabbitmq_1:
    image: rabbitmq:3.9
    restart: unless-stopped
    hostname: rabbitmq_1
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
    networks:
      - rabbitmq
    #volumes:
    #  - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.conf:ro

networks:
  rabbitmq:
    name: rabbitmq
